name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        toolchain:
          - stable
          # we need 1.58 as it has format strings
          - 1.58

    steps:

      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Install cargo check-all
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-all-features --force

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check-all-features
          args: --target wasm32-unknown-unknown

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: --target wasm32-unknown-unknown

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target wasm32-unknown-unknown -- -D warnings
